### ISSUE TITLE
Handwrite error in MatrixXd.h

### ISSUE THREAD

**Issue by xyat21** [MatMechLab/AsFem#37]
In line 168 of the file AsFem/include/Utils/MatrixXd.h, there is a typing error, it should be ' * ' rather than '+'.
`
//*** for *

    inline MatrixXd operator*(const double &val)const{

        MatrixXd temp(_M,_N);

        for(int i=0;i<_MN;++i) temp._vals[i]=_vals[i]+val;

        return temp;

    }
`

The line should be
`
for(int i=0;i<_MN;++i) temp._vals[i]=_vals[i]*val;
`

**Comment by yangbai90** [comment]
Hi @xyat21 , 
 Thank you very much for your feedback. 
The issue has now been resolved in ab769485ff8a58cb4d7d98593be532075907256f
