### ISSUE TITLE
Written error in AnaqusIO.h

### ISSUE THREAD

**Issue by xyat21** [MatMechLab/AsFem#38]
In line 47 of file AsFem\include\Mesh\AnaqusIO.h, the defined getfun should be GetSubElmtDimFromInp() rather than GetSubElmtDimFromGmshInp(), since this is AbaqusIO importer definition.

**Comment by yangbai90** [comment]
Hi @xyat21 ,
Thanks for poiting out the typo, now it is fixed in 0f9c06721b1ae43db6b5d65a98e9129810beb406
BR
Yang
