### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by chenhhu** [MatMechLab/AsFem#5]
Thank you very much for your open source. It would be even better to output the results in a folder.

**Comment by yangbai90** [comment]
Now, I find cpp17 has a built-in API for folder creation, the filesystem::create_directory function. Some modification has been made based on this: https://github.com/yangbai90/AsFem/commit/b3570637af2ebce5e3f4cf6996e69ca36e6e9738

Now users can use the [output] block to define a folder name, then the result can be written out to the specific folder. For example:
[output]
 type=vtu // this line can be ignored, currently, we only talk with the vtu file format
folder=test
[end]

A complete test example can be found here:
https://github.com/yangbai90/AsFem/blob/devel/tests/poisson/quad4_linear.i
